[workspace]
default-members = ["example"]
members = [
  "crates/gpui-storybook",
  "crates/gpui-storybook-core",
  "crates/gpui-storybook-macros",
  "example",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/stayhydated/gpui-storybook"
rust-version = "1.88"
version = "0.5.0"

[workspace.dependencies]
anyhow = "1.0"
automod = "1.0"
bon = "3.8"
chrono = "0.4"
crabtime = "1.1"
crate-paths = "0.2"
darling = "0.23"
derive_more = "2.1"
dotenv = "0.15"
es-fluent = { git = "https://github.com/stayhydated/es-fluent", branch = "proper-locales" }
es-fluent-lang = { git = "https://github.com/stayhydated/es-fluent", branch = "proper-locales" }
es-fluent-manager-embedded = { git = "https://github.com/stayhydated/es-fluent", branch = "proper-locales" }
fake = "4.4"
fluent-bundle = "0.16"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
gpui-storybook = { path = "crates/gpui-storybook", version = "0.5.0" }
gpui-storybook-core = { path = "crates/gpui-storybook-core", version = "0.5.0" }
gpui-storybook-macros = { path = "crates/gpui-storybook-macros", version = "0.5.0" }
heck = "0.5"
insta = { version = "1.46" }
inventory = "0.3"
itertools = "0.14"
log = "0.4"
once_cell = "1.21"
paste = "1.0"
prettyplease = "0.2"
proc-macro-error2 = "2"
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.9"
rayon = "1.11"
regex = "1.12"
reqwest_client = { git = "https://github.com/longbridge/gpui-component" }
rust-embed = "8.11"
rust_decimal = "1.40"
serde = "1.0"
serde_json = "1.0"
strum = "0.27"
syn = "2.0"
thiserror = "2.0"
tokio = "1.49"
tracing = "0.1"
tracing-subscriber = "0.3"
unic-langid = "0.9"
unicode-segmentation = "1.12"

[workspace.lints.rust]
unexpected_cfgs = { level = "deny" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
type_complexity = "allow"
uninlined_format_args = "allow"
unused_trait_names = "warn"

[profile.dev]
codegen-units = 16
debug = "limited"
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
