[workspace]
default-members = [ "example" ]
members = [
  "crates/gpui-storybook",
  "crates/gpui-storybook-core",
  "crates/gpui-storybook-macros",
  "example",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/stayhydated/gpui-storybook"
rust-version = "1.88"
version = "0.5.0"

[workspace.dependencies]
anyhow = "1.0.100"
automod = "1.0.16"
bon = "3.8.2"
chrono = "0.4.43"
crabtime = "1.1.4"
crate-paths = "0.2.0"
darling = "0.23.0"
derive_more = "2.1.1"
dotenv = "0.15.0"
es-fluent = "0.5.3"
es-fluent-lang = "0.5.3"
es-fluent-manager-embedded = "0.5.3"
fake = "4.4.0"
fluent-bundle = "0.16.0"
gpui = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
gpui-storybook = { path = "crates/gpui-storybook", version = "0.5.0" }
gpui-storybook-core = { path = "crates/gpui-storybook-core", version = "0.5.0" }
gpui-storybook-macros = { path = "crates/gpui-storybook-macros", version = "0.5.0" }
heck = "0.5.0"
insta = { version = "1.46.1" }
inventory = "0.3.21"
itertools = "0.14.0"
log = "0.4.29"
once_cell = "1.21.3"
paste = "1.0.15"
prettyplease = "0.2.37"
proc-macro-error2 = "2.0"
proc-macro2 = "1.0.105"
quote = "1.0.43"
rand = "0.8"
rayon = "1.11.0"
regex = "1.12.2"
reqwest_client = { git = "https://github.com/longbridge/gpui-component" }
rust-embed = "8.11.0"
rust_decimal = "1.40.0"
serde = "1.0.228"
serde_json = "1.0.149"
strum = "0.27.2"
syn = "2.0.114"
thiserror = "2.0.17"
tokio = "1.49.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
unic-langid = "0.9.6"
unicode-segmentation = "1.12.0"
unwrapped = { default-features = false, version = "0.1.2" }
unwrapped-core = { version = "0.1.2" }

[workspace.lints.rust]
unexpected_cfgs = { level = "deny" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
type_complexity = "allow"
uninlined_format_args = "allow"
unused_trait_names = "warn"

[profile.dev]
codegen-units = 16
debug = "limited"
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
